# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 052d366a10e50df114b366c09a4c7b5578448349dd19fc2bf89b07d57273323ac5bac3d1842f471f3669879cb605222ad22860660ed82bf1f6eb616befa0c89b

test:
  secret_key_base: 6d6fc5dfa2c312ad047bf4494cb3d4a8980c751fd4fcba91aa86d379bd15597f78754528d67d3995bcde7d5e8f99a8db096869e398b4f488f665b81d5b51e31f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
